### ISSUE TITLE
Update to .net 8 ? 

### ISSUE THREAD

**Issue by orosbogdan** [ghostnguyen/HttpClientFillerIssue#1]
Could you please update the library to .net 8 ?

**Comment by ghostnguyen** [comment]
It should be compatible with .Net 8

**Comment by psulek** [comment]
@orosbogdan As u can see in [nuget package/supported fws](https://www.nuget.org/packages/HttpClientFiller#supportedframeworks-body-tab) it is compatible with NET8.
