### ISSUE TITLE
MIT or LGPL over GPL license?

### ISSUE THREAD

**Issue by michael-hawker** [ghostnguyen/HttpClientFillerIssue#2]
Hi, I saw your post on the Refit issue about AoT, so I wanted to check-out what you had here available from NuGet and GitHub.

However, I see the project is licensed under GPL like an application, over a more library friendly LGPL or MIT license (like Refit itself is).

GPL means that even just linking/using the library from the NuGet package requires anyone else to also comply their whole application with the GPL terms vs. just being scoped to your library's code as a dependency. See this FAQ question: https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

Just wanted to call this out as it may hurt adoption of your library, if that's what you're looking for. Thanks!

**Comment by michael-hawker** [comment]
Also just noticed this which is confusing in a couple of cases/relation to this question:

https://github.com/ghostnguyen/HttpClientFillerIssue/blob/f84b643c00b34be8e88d243ea844a66d58b029ab/HttpClientFillerCore/HttpClientFillerCore.csproj#L13

**Comment by ghostnguyen** [comment]
Update license file to MIT.
